// This file is autogenerated by scripts/generate-nav-config.mts
// Do not edit this file directly.

export const contentConfig = {
  "courses": [
    {
      "title": "Компьютерные сети",
      "description": "В этом курсе мы подробно рассмотрим устройство и принципы работы компьютерных сетей.",
      "slug": "/courses/computer-networks",
      "publishedAt": "2024-01-01"
    }
  ],
  "labs": [
    {
      "title": "BASH script development",
      "slug": "/labs/bash-script-development",
      "publishedAt": "2024-01-01"
    },
    {
      "title": "Lab Network Engineer CCNA & CCNP level",
      "description": "This is between the CCNA & CCNP level. And it's not just limited to cisco. The objective is to put yourself in a real situation, both as an internet provider, as a company with several sites. This might not be an optimal configuration for this kind of architecture, but it may help sharpen the weapons.",
      "slug": "/labs/ccna-advance",
      "publishedAt": "2024-01-01"
    },
    {
      "title": "Datacenter",
      "description": "Complete architecture of datacenter",
      "slug": "/labs/datacenter",
      "publishedAt": "2024-01-01"
    },
    {
      "title": "Enterprise Network Lab: Bank Project",
      "slug": "/labs/enterprise-network-lab-bank-project",
      "publishedAt": "2024-01-01"
    },
    {
      "title": "Enterprise Network",
      "slug": "/labs/enterprise-network",
      "publishedAt": "2024-01-01"
    },
    {
      "title": "MPLS Standard Network Lab",
      "description": "Building an MPLS network so that Customer-A can reach Customer-B through MPLS backbone",
      "slug": "/labs/mpls-standard-network-lab",
      "publishedAt": "2024-01-01"
    },
    {
      "title": "Simple Network Layout",
      "description": "Preconfigured network to practice on in GNS3",
      "slug": "/labs/simple-network-layout",
      "publishedAt": "2024-01-01"
    },
    {
      "title": "VLANS and DHCP",
      "slug": "/labs/vlans-and-dhcp-2",
      "publishedAt": "2024-01-01"
    }
  ]
}

export type ContentConfig = typeof contentConfig

