worker_processes 4;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        listen [::]:80;
        server_name localhost;

        location / {
            proxy_pass http://netlab_frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/ {
            proxy_pass http://netlab_server:8000/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # GNS3 Lab
        location /lab/ {
            proxy_pass http://netlab_lab:3080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Rewrite redirects and URLs
            proxy_redirect http://$host:3080/ /lab/;
            proxy_redirect /static/web-ui/ /lab/static/web-ui/;
            
            sub_filter_once off;
            sub_filter_types *;
            sub_filter 'http://localhost:3080' '/lab';
            sub_filter 'href="/static' 'href="/lab/static';
            sub_filter 'src="/static' 'src="/lab/static';
            sub_filter 'action="/static' 'action="/lab/static';
        }

        # Block restricted GNS3 routes
        location ~ ^/lab/static/web-ui/controller/1/(preferences|image-manager|controllers) {
            deny all;
            return 403;
        }

        # http://127.0.0.1:3080/static/web-ui/controller/1/projects
    }
}