import { promises as fs } from "fs"
import path from "path"
import { allDocuments } from "../.contentlayer/generated/index.mjs"

const OUTPUT_PATH = path.join(process.cwd(), "/src/shared/config/content.ts")

async function buildContentConfig() {
  const contentConfig: Record<string, { title: string; description: string; slug: string; publishedAt: string }[]> = {};

  const filteredRootAllDocuments = allDocuments.filter((doc) => doc.sortOrder === 0 || !doc.sortOrder)

  for (const doc of filteredRootAllDocuments) {
    const { title, description, slug, publishedAt, ...rest } = doc;

    const type = `${rest.type.toLowerCase()}s`;

    if (!contentConfig[type]) {
      contentConfig[type] = []
    }

    contentConfig[type].push({
      title,
      description,
      slug,
      publishedAt,
    })
  }

  return contentConfig
}

async function generateContentConfig() {
  const contentConfig = await buildContentConfig()
  const contentConfigString = JSON.stringify(contentConfig, null, 2)

  const fileContent = `// This file is autogenerated by scripts/generate-nav-config.mts
// Do not edit this file directly.

export const contentConfig = ${contentConfigString}

export type ContentConfig = typeof contentConfig

`

  await fs.writeFile(OUTPUT_PATH, fileContent, "utf8")
}

try {
  console.log("💽 Building contentConfig...")
  await generateContentConfig()
  console.log("✅ Done!")
} catch (error) {
  console.error(error)
  process.exit(1)
}