[Controller]

; Options for JWT tokens (user authentication)
jwt_secret_key = efd08eccec3bd0a1be2e086670e5efa90969c68d07e072d7354a76cea5e33d4e
jwt_algorithm = HS256
; 1440 mins = 1 day
jwt_access_token_expire_minutes = 1440

; Initial default super admin username
; It cannot be changed once the controller has started once
default_admin_username = admin
; Initial default super admin password
; It cannot be changed once the controller has started once
default_admin_password = admin


[Server]

; Ensure legacy auth is disabled
auth = False

; IP where the server listen for connection
host = 0.0.0.0
; HTTP port for controlling the servers
port = 3080
; Path where images of devices are stored
images_path = /data/images
; Path where user project are stored
projects_path = /data/projects

appliances_path = /data/appliances
; Send crash to the GNS3 team
report_errors = False
; First port of the range allocated to devices telnet console
console_start_port_range = 2001
; Last port of the range allocated to devices telnet console
console_end_port_range = 5000
; First port of the range allocated to communication between devices. You need two port by link
udp_start_port_range = 10000
; Last port of the range allocated to communication between devices. You need two port by link
udp_start_end_range = 20000
; Path of the ubridge program
ubridge_path = /usr/bin/ubridge

; NOT VALID ANYMORE (in 2.2.51 was working)
; USE INSTEAD default_admin_username
; Boolean for enabling HTTP auth
; auth = True
; ; Username for HTTP auth
; user = admin
; ; Password for HTTP auth
; password = 1234

[VPCS]
; Path of the VPCS binary
vpcs_path = /usr/bin/vpcs
 
[Dynamips]
allocate_aux_console_ports = False
mmap_support = True
; Path of the dynamips path
dynamips_path = /usr/bin/dynamips
sparse_memory_support = True
ghost_ios_support = True
 
[IOU]
; Path of the iouyap binary
iouyap_path = /usr/bin/iouyap
; Path of your .iourc file. If empty we search in $HOME/.iourc
iourc_path = /data/.iourc
; Validate if the iourc is correct. If you turn off and your licence is invalid iou will crash without errors
license_check = True

[Qemu]
enable_kvm = True
require_kvm = True
